mariadb:
  enabled: false

wordpress:
  namespace: default
  wordpressPassword: foo
  mariadb:
    enabled: false
  externalDatabase:
    host: localhost
    user: bn_wordpress
    password: ""
    database: bitnami_wordpress
    port: 3306