architecture: replication

auth:
  enabled: true
  password: "Doifo4Pj44"
  sentinel: true

replicaCount: 3     # This gives you 1 Master + 1 Replica = 2 Nodes total

sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi